title:              Informapédia
email:              web.concib@gmail.com
description:        Uma página para que você saiba das informações, notícias do Brasil e do Mundo. As informações aqui postadas são verificadas por bibliotecários e bibliotecárias quanto a sua veracidade.
author:             WebConCib
baseurl:            ""
url:                "https://infomapedia.github.io"

defaults:
  - scope:
      path: ""
    values:
      image: favicon.ico

facebook:
  app_id: 4036278873112896
# Social Profiles
#twitter_username:   SBootstrap
github_username:    Informapedia
facebook_username:  WebConCib
instagram_username:  webconcib
linkedin_username:
youtube_username: UCCbMauCCNarGd8Wjkq5TMqg

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-168721960-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site.
